### ISSUE TITLE
Unused label

### ISSUE THREAD

**Issue by sen1** [paulschraven/intro-data-capstone-biodiversity#1]
https://github.com/paulschraven/intro-data-capstone-biodiversity/blob/1964624194098eca671099f482875924c31e310d/PaulSchraven_FinalProjectCodecademy/PaulSchraven_FinalProject.py#L58

You can get the xticks labels by using get_xticklabels(). This is something we didnt cover in our course. So good job. Since this is a simple bar plot you wont need additional labels. Label variable is left unused in your code.

**Comment by paulschraven** [comment]
Alright, got it!
