### ISSUE TITLE
Multiple fillna

### ISSUE THREAD

**Issue by sen1** [paulschraven/intro-data-capstone-biodiversity#2]
https://github.com/paulschraven/intro-data-capstone-biodiversity/blob/1964624194098eca671099f482875924c31e310d/PaulSchraven_FinalProjectCodecademy/PaulSchraven_FinalProject.py#L44

You already have fillna() in line 22. Calling fillna() again is useless since null values already been replaced. To check if your dataframe still have some null values present, you can do:
species.isnull().sum()

It should show all 0s if all null values are filled up.

**Comment by paulschraven** [comment]
Makes sense!
