### ISSUE TITLE
Repeated code

### ISSUE THREAD

**Issue by sen1** [paulschraven/intro-data-capstone-biodiversity#3]
https://github.com/paulschraven/intro-data-capstone-biodiversity/blob/1964624194098eca671099f482875924c31e310d/PaulSchraven_FinalProjectCodecademy/PaulSchraven_FinalProject.py#L81-L99

You have some repeated codes in there. There wrong but when you create a new variable with the same name, it will replace the old one.

**Comment by paulschraven** [comment]
I assume that's due to copy-pasting from Codecademy :)
