### ISSUE TITLE
Common column

### ISSUE THREAD

**Issue by sen1** [paulschraven/intro-data-capstone-biodiversity#4]
https://github.com/paulschraven/intro-data-capstone-biodiversity/blob/1964624194098eca671099f482875924c31e310d/PaulSchraven_FinalProjectCodecademy/PaulSchraven_FinalProject.py#L132

Code looks great. It gets the job done. Just a small tip that by default merge looks for common column names and merge column with column. So if you would say:
 sheep_observations = pd.merge(sheep_species, observations)
That would work just fine.
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html

**Comment by paulschraven** [comment]
Good to know!
