### ISSUE TITLE
Wrong values

### ISSUE THREAD

**Issue by sen1** [paulschraven/intro-data-capstone-biodiversity#6]
https://github.com/paulschraven/intro-data-capstone-biodiversity/blob/1964624194098eca671099f482875924c31e310d/PaulSchraven_FinalProjectCodecademy/PaulSchraven_FinalProject.py#L166-L172

Here is the link to the calculator again:
https://www.optimizely.com/sample-size-calculator/?conversion=15&effect=33.3&significance=90
This will give you sample_size_per_variant=510

This will change your next two answers:
bryce = 510 / 250.
yellowstone = 510 / 507.

Approximately 2 weeks at Bryce and 1 week at Yellowstone.

**Comment by paulschraven** [comment]
Thanks! I assume you fixed the calculator since then? Since the one in the project didn't work for me
