### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by sen1** [paulschraven/intro-data-capstone-biodiversity#7]
Great work! I probably won’t have much to say here because you pretty much nailed it all the way through.

Your Python work was excellent and very readable. There were some repeated codes in your script. It could be just a copy-paste error while you were coping code from codecademy to jupyter. However, everything worked the way it was supposed to.

Presentation: I think your graphs look excellent. You mentioned in disclaimer that you had trouble finding the correct link for sample size calculations. I sent you the correct one in another issue. The link you posted can not be open. Anyway overall you did a good job.

Excellent work overall.

**Comment by paulschraven** [comment]
Thank you very much :)
